
services:
  app:
    container_name: golang_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=postgresdb
      - DBPORT=5432
      - DBNAME=${DBNAME}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - api_net

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://app:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - api_net

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - api_net

networks:
  api_net:
    driver: bridge

volumes:
  postgres_data:
